#tomcat
server:
  port: 8082

#dubbo配置
dubbo:
  registry:
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 30001
    
# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    #activemq
    activemq:
      broker-url: tcp://localhost:61616
      in-memory: true
      pool:
        enabled: false

#mybatis配置
mybatis:
  type-aliases-package: com.lemon.common.model
  config-locations: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  
#pagehelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
