# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 1002
    #context-path: /lemon-member

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    application:
      name: lemon-member
    #邮件配置
    mail:
      host: smtp.163.com
      username: runner1920@163.com  
      password: jxl671768276
      properties:  
          mail:   
              smtp:  
                  auth: true  
                  timeout: 25000 

#Mybatis配置
mybatis:
  type-aliases-package: com.lemon.common.model.sys
  configLocation: classpath:mybatis.xml
  mapperLocations: classpath:mapper/*.xml
  
#pagehelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
#SpringCloud配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://lemon-eureka:1001/eureka/
feign:
  hystrix:
    enabled: true