# Tomcat
server:
    port: 8001
    #context-path: /lemon-config

# mysql
spring:
    application:
      name: lemon-config
    #邮件配置
    cloud:
      config:
        server:
          git:
            #配置git仓库的地址
            uri: https://gitee.com/runner1920/cloud-config.git
            #git仓库地址下的相对地址，可以配置多个，用,分割。
            search-paths: config
            #用户名
            username: runner1920@163.com
            #密码
            password: jiang,3413
